import React, { useState, useEffect } from "react";
import { format } from "date-fns";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const getToday = () => format(new Date(), "yyyy-MM-dd");

function App() {
  const [selectedDate, setSelectedDate] = useState(getToday());
    const [deliveries, setDeliveries] = useState(() => {
        const saved = localStorage.getItem("deliveries");
            return saved ? JSON.parse(saved) : {};
              });

                const [price, setPrice] = useState(() => {
                    return Number(localStorage.getItem("price")) || 20;
                      });

                        const [priceHistory, setPriceHistory] = useState(() => {
                            const saved = localStorage.getItem("priceHistory");
                                return saved ? JSON.parse(saved) : [{ date: getToday(), price: 20 }];
                                  });

                                    const [paidMonths, setPaidMonths] = useState(() => {
                                        const saved = localStorage.getItem("paidMonths");
                                            return saved ? JSON.parse(saved) : [];
                                              });

                                                // Save changes
                                                  useEffect(() => {
                                                      localStorage.setItem("deliveries", JSON.stringify(deliveries));
                                                          localStorage.setItem("price", price);
                                                              localStorage.setItem("priceHistory", JSON.stringify(priceHistory));
                                                                  localStorage.setItem("paidMonths", JSON.stringify(paidMonths));
                                                                    }, [deliveries, price, priceHistory, paidMonths]);

                                                                      // Notification reminder at 8 AM
                                                                        useEffect(() => {
                                                                            if (Notification.permission !== "granted") {
                                                                                  Notification.requestPermission();
                                                                                      }

                                                                                          const checkAndNotify = () => {
                                                                                                const now = new Date();
                                                                                                      const targetHour = 8;
                                                                                                            const alreadyNotified = localStorage.getItem("notifiedDate") === format(now, "yyyy-MM-dd");

                                                                                                                  if (now.getHours() === targetHour && !alreadyNotified) {
                                                                                                                          new Notification("Reminder: Mark your water bottle delivery!");
                                                                                                                                  localStorage.setItem("notifiedDate", format(now, "yyyy-MM-dd"));
                                                                                                                                        }
                                                                                                                                            };

                                                                                                                                                const interval = setInterval(checkAndNotify, 60 * 1000);
                                                                                                                                                    return () => clearInterval(interval);
                                                                                                                                                      }, []);

                                                                                                                                                        const toggleDelivery = (date) => {
                                                                                                                                                            setDeliveries((prev) => ({
                                                                                                                                                                  ...prev,
                                                                                                                                                                        [date]: prev[date] === "delivered" ? "skipped" : "delivered",
                                                                                                                                                                            }));
                                                                                                                                                                              };

                                                                                                                                                                                const changePrice = (newPrice) => {
                                                                                                                                                                                    const today = getToday();
                                                                                                                                                                                        setPrice(newPrice);
                                                                                                                                                                                            setPriceHistory((prev) => [...prev, { date: today, price: Number(newPrice) }]);
                                                                                                                                                                                              };

                                                                                                                                                                                                const getPriceForDate = (date) => {
                                                                                                                                                                                                    const sorted = [...priceHistory].sort((a, b) => new Date(b.date) - new Date(a.date));
                                                                                                                                                                                                        for (const p of sorted) {
                                                                                                                                                                                                              if (new Date(date) >= new Date(p.date)) return p.price;
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                      return price;
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                          const getMonthlySummary = (month) => {
                                                                                                                                                                                                                              let total = 0;
                                                                                                                                                                                                                                  let cost = 0;
                                                                                                                                                                                                                                      for (const date in deliveries) {
                                                                                                                                                                                                                                            if (deliveries[date] === "delivered" && date.startsWith(month)) {
                                                                                                                                                                                                                                                    total++;
                                                                                                                                                                                                                                                            cost += getPriceForDate(date);
                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                          return { total, cost };
                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                              const generatePDF = async () => {
                                                                                                                                                                                                                                                                                  const summaryEl = document.getElementById("summary-card");
                                                                                                                                                                                                                                                                                      const canvas = await html2canvas(summaryEl);
                                                                                                                                                                                                                                                                                          const imgData = canvas.toDataURL("image/png");

                                                                                                                                                                                                                                                                                              const pdf = new jsPDF("p", "mm", "a4");
                                                                                                                                                                                                                                                                                                  const imgProps = pdf.getImageProperties(imgData);
                                                                                                                                                                                                                                                                                                      const pdfWidth = pdf.internal.pageSize.getWidth();
                                                                                                                                                                                                                                                                                                          const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

                                                                                                                                                                                                                                                                                                              pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
                                                                                                                                                                                                                                                                                                                  pdf.save("Water_Summary_" + month + ".pdf");
                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                      const month = selectedDate.slice(0, 7);
                                                                                                                                                                                                                                                                                                                        const { total, cost } = getMonthlySummary(month);
                                                                                                                                                                                                                                                                                                                          const paid = paidMonths.includes(month);
                                                                                                                                                                                                                                                                                                                            const status = deliveries[selectedDate] || "delivered";

                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: 16, fontFamily: "Arial", maxWidth: 420, margin: "auto" }}>
                                                                                                                                                                                                                                                                                                                                        <h2 style={{ textAlign: "center", marginBottom: 20 }}>💧 Water Bottle Tracker</h2>

                                                                                                                                                                                                                                                                                                                                              <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                      <h3>Choose Date</h3>
                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                        type="date"
                                                                                                                                                                                                                                                                                                                                                                                  value={selectedDate}
                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setSelectedDate(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                      style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>Delivery Status</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={infoText}>{selectedDate}: <strong>{status}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={buttonStyle} onClick={() => toggleDelivery(selectedDate)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Mark as {status === "skipped" ? "Delivered" : "Skipped"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>Bottle Price</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => changePrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div id="summary-card" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>{month} Summary</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={infoText}>Bottles Delivered: <strong>{total}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={infoText}>Total Cost: <strong>₹{cost}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={infoText}>Payment Status: <strong>{paid ? "Paid" : "Unpaid"}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={infoText}>Daily Breakdown:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {Object.entries(deliveries)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .filter(([date]) => date.startsWith(month))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .map(([date, status]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p key={date} style={{ fontSize: 14 }}>{date}: {status}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ ...buttonStyle, backgroundColor: paid ? "#999" : "#007bff" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setPaidMonths((prev) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  paid ? prev.filter(m => m !== month) : [...prev, month]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Mark as {paid ? "Unpaid" : "Paid"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ ...buttonStyle, backgroundColor: "#28a745" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={generatePDF}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Download Monthly Summary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const cardStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: "#f9f9f9",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: "1px 1px 6px rgba(0,0,0,0.1)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const buttonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "10px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: "#007bff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginRight: 10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const infoText = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              