// App.js
import React, { useEffect, useState } from "react";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import './App.css';
import { getDatabase, ref, onValue, set } from "firebase/database";
import { initializeApp } from "firebase/app";
import jsPDF from "jspdf";
import "jspdf-autotable";

const firebaseConfig = {
  apiKey: "AIzaSyDcjLslqHE4cD4YhVkS9M4SGYuJ02bT8sY",
    authDomain: "watersubstracker.firebaseapp.com",
      projectId: "watersubstracker",
        storageBucket: "watersubstracker.firebasestorage.app",
          messagingSenderId: "337275338555",
            appId: "1:337275338555:web:57ac0c213170d8c8dc811e",
              databaseURL: "https://watersubstracker-default-rtdb.asia-southeast1.firebasedatabase.app/"
              };

              const app = initializeApp(firebaseConfig);
              const db = getDatabase(app);

              export default function App() {
                const [selectedDate, setSelectedDate] = useState(new Date());
                  const [deliveries, setDeliveries] = useState({});
                    const [price, setPrice] = useState(0);
                      const [paidStatus, setPaidStatus] = useState({});

                        useEffect(() => {
                            const deliveriesRef = ref(db, "deliveries");
                                const priceRef = ref(db, "price");
                                    const paidRef = ref(db, "paidStatus");

                                        onValue(deliveriesRef, (snapshot) => {
                                              setDeliveries(snapshot.val() || {});
                                                  });

                                                      onValue(priceRef, (snapshot) => {
                                                            setPrice(snapshot.val() || 0);
                                                                });

                                                                    onValue(paidRef, (snapshot) => {
                                                                          setPaidStatus(snapshot.val() || {});
                                                                              });
                                                                                }, []);

                                                                                  const formatDate = (date) => date.toISOString().split("T")[0];

                                                                                    const handleMarkDelivered = () => {
                                                                                        const dateStr = formatDate(selectedDate);
                                                                                            const updatedDeliveries = { ...deliveries, [dateStr]: true };
                                                                                                set(ref(db, "deliveries"), updatedDeliveries);
                                                                                                  };

                                                                                                    const handleMarkSkipped = () => {
                                                                                                        const dateStr = formatDate(selectedDate);
                                                                                                            const updatedDeliveries = { ...deliveries, [dateStr]: false };
                                                                                                                set(ref(db, "deliveries"), updatedDeliveries);
                                                                                                                  };

                                                                                                                    const handlePriceChange = (e) => {
                                                                                                                        const newPrice = parseFloat(e.target.value);
                                                                                                                            if (!isNaN(newPrice)) {
                                                                                                                                  set(ref(db, "price"), newPrice);
                                                                                                                                      }
                                                                                                                                        };

                                                                                                                                          const togglePaidStatus = (monthKey) => {
                                                                                                                                              const updatedStatus = { ...paidStatus, [monthKey]: !paidStatus[monthKey] };
                                                                                                                                                  set(ref(db, "paidStatus"), updatedStatus);
                                                                                                                                                    };

                                                                                                                                                      const getMonthlySummary = () => {
                                                                                                                                                          const summary = {};
                                                                                                                                                              for (const dateStr in deliveries) {
                                                                                                                                                                    const [year, month] = dateStr.split("-");
                                                                                                                                                                          const key = `${year}-${month}`;
                                                                                                                                                                                if (!summary[key]) summary[key] = { count: 0, total: 0 };
                                                                                                                                                                                      if (deliveries[dateStr]) summary[key].count += 1;
                                                                                                                                                                                          }
                                                                                                                                                                                              for (const key in summary) {
                                                                                                                                                                                                    summary[key].total = summary[key].count * price;
                                                                                                                                                                                                        }
                                                                                                                                                                                                            return summary;
                                                                                                                                                                                                              };

                                                                                                                                                                                                                const exportPDF = () => {
                                                                                                                                                                                                                    const summary = getMonthlySummary();
                                                                                                                                                                                                                        const doc = new jsPDF();
                                                                                                                                                                                                                            const rows = Object.keys(summary).map((month) => [
                                                                                                                                                                                                                                  month,
                                                                                                                                                                                                                                        summary[month].count,
                                                                                                                                                                                                                                              `₹${summary[month].total}`,
                                                                                                                                                                                                                                                    paidStatus[month] ? "Paid" : "Unpaid"
                                                                                                                                                                                                                                                        ]);
                                                                                                                                                                                                                                                            doc.autoTable({ head: [["Month", "Bottles", "Total", "Status"]], body: rows });
                                                                                                                                                                                                                                                                doc.save("summary.pdf");
                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                    const selectedDateStr = formatDate(selectedDate);
                                                                                                                                                                                                                                                                      const summary = getMonthlySummary();

                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                            <div style={{ padding: 20, fontFamily: "Arial" }}>
                                                                                                                                                                                                                                                                                  <h2>💧 Water Bottle Tracker</h2>
                                                                                                                                                                                                                                                                                        <Calendar onChange={setSelectedDate} value={selectedDate} />
                                                                                                                                                                                                                                                                                              <p>Selected Date: {selectedDateStr}</p>
                                                                                                                                                                                                                                                                                                    <button onClick={handleMarkDelivered} style={{ marginRight: 10 }}>Mark as Delivered</button>
                                                                                                                                                                                                                                                                                                          <button onClick={handleMarkSkipped}>Mark as Skipped</button>

                                                                                                                                                                                                                                                                                                                <div style={{ marginTop: 20 }}>
                                                                                                                                                                                                                                                                                                                        <label>Bottle Price: ₹</label>
                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                          type="number"
                                                                                                                                                                                                                                                                                                                                                    value={price}
                                                                                                                                                                                                                                                                                                                                                              onChange={handlePriceChange}
                                                                                                                                                                                                                                                                                                                                                                        style={{ width: 80, marginLeft: 5 }}
                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                            <h3 style={{ marginTop: 30 }}>Monthly Summary</h3>
                                                                                                                                                                                                                                                                                                                                                                                                  <table border="1" cellPadding="8">
                                                                                                                                                                                                                                                                                                                                                                                                          <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Month</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Delivered</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Total</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <th>Status</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Toggle</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {Object.keys(summary).map((monthKey) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr key={monthKey}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td>{monthKey}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>{summary[monthKey].count}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>₹{summary[monthKey].total}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>{paidStatus[monthKey] ? "Paid" : "Unpaid"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => togglePaidStatus(monthKey)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {paidStatus[monthKey] ? "Unmark" : "Mark Paid"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={exportPDF} style={{ marginTop: 20 }}>Export PDF</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      