import React, { useState } from "react";
import { format } from "date-fns";

const getToday = () => format(new Date(), "yyyy-MM-dd");

function App() {
  const [deliveries, setDeliveries] = useState({});
    const [price, setPrice] = useState(20);
      const [priceHistory, setPriceHistory] = useState([{ date: getToday(), price: 20 }]);
        const [paidMonths, setPaidMonths] = useState([]);

          const today = getToday();
            const thisMonth = today.slice(0, 7);

              const toggleDelivery = (date) => {
                  setDeliveries((prev) => ({
                        ...prev,
                              [date]: prev[date] === "delivered" ? "skipped" : "delivered",
                                  }));
                                    };

                                      const changePrice = (newPrice) => {
                                          const today = getToday();
                                              setPrice(newPrice);
                                                  setPriceHistory((prev) => [...prev, { date: today, price: Number(newPrice) }]);
                                                    };

                                                      const getPriceForDate = (date) => {
                                                          const sorted = [...priceHistory].sort((a, b) => new Date(b.date) - new Date(a.date));
                                                              for (const p of sorted) {
                                                                    if (new Date(date) >= new Date(p.date)) return p.price;
                                                                        }
                                                                            return price;
                                                                              };

                                                                                const getMonthlySummary = (month) => {
                                                                                    let total = 0;
                                                                                        let cost = 0;
                                                                                            for (const date in deliveries) {
                                                                                                  if (deliveries[date] === "delivered" && date.startsWith(month)) {
                                                                                                          total++;
                                                                                                                  cost += getPriceForDate(date);
                                                                                                                        }
                                                                                                                            }
                                                                                                                                return { total, cost };
                                                                                                                                  };

                                                                                                                                    const { total, cost } = getMonthlySummary(thisMonth);
                                                                                                                                      const paid = paidMonths.includes(thisMonth);

                                                                                                                                        return (
                                                                                                                                            <div style={{ padding: 20, fontFamily: "Arial", maxWidth: 420, margin: "auto" }}>
                                                                                                                                                  <h2 style={{ textAlign: "center", marginBottom: 20 }}>💧 Water Bottle Tracker</h2>

                                                                                                                                                        <div style={cardStyle}>
                                                                                                                                                                <h3>Today's Delivery</h3>
                                                                                                                                                                        <p style={infoText}>{today}: <strong>{deliveries[today] || "delivered"}</strong></p>
                                                                                                                                                                                <button style={buttonStyle} onClick={() => toggleDelivery(today)}>
                                                                                                                                                                                          Mark as {deliveries[today] === "skipped" ? "Delivered" : "Skipped"}
                                                                                                                                                                                                  </button>
                                                                                                                                                                                                        </div>

                                                                                                                                                                                                              <div style={cardStyle}>
                                                                                                                                                                                                                      <h3>Bottle Price</h3>
                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                        type="number"
                                                                                                                                                                                                                                                  value={price}
                                                                                                                                                                                                                                                            onChange={(e) => changePrice(e.target.value)}
                                                                                                                                                                                                                                                                      style={inputStyle}
                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                          <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                  <h3>{thisMonth} Summary</h3>
                                                                                                                                                                                                                                                                                                          <p style={infoText}>Bottles Delivered: <strong>{total}</strong></p>
                                                                                                                                                                                                                                                                                                                  <p style={infoText}>Total Cost: <strong>₹{cost}</strong></p>
                                                                                                                                                                                                                                                                                                                          <button style={buttonStyle} onClick={() =>
                                                                                                                                                                                                                                                                                                                                    setPaidMonths((prev) =>
                                                                                                                                                                                                                                                                                                                                                paid ? prev.filter(m => m !== thisMonth) : [...prev, thisMonth]
                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                  }>
                                                                                                                                                                                                                                                                                                                                                                            Mark as {paid ? "Unpaid" : "Paid"}
                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                const cardStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                  background: "#f9f9f9",
                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                        padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                            boxShadow: "2px 2px 6px rgba(0,0,0,0.1)"
                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                            const buttonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                              padding: "10px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: "#007bff",
                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 10
                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                            const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc"
                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                    const infoText = {
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 16
                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                      export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                      